### ISSUE TITLE
Gør sådan at det er en mulighed at bruge "/transporter put mine" når man bruger auto transporter.

### ISSUE THREAD

**Issue by TFSMads** [TFSMads/transporter#11]
Dette vil dog kræve at transporter put mine og transporter info blev skrevet skifte vis dog ville det stadig være hurtigere end at skrive en kommando for hver item og det ville sikre at data om transporter indholdet altid var præcis.

**Comment by TheAncientBook** [comment]
Man kan vel skjule indholdet, når /transporter info bliver skrevet, dog kun i tilfælde hvor det er nødvendigt. Folk skal jo være i stand til at bruge kommandoen selv og se hvad de nu ahr.

**Comment by TFSMads** [comment]
Ja det var også det jeg tænkte. Dog kunne man også bare kigge hvilke items spilleren har i inventoryet inden kommandoen og efter og udregne antalet af items i transporteren ud fra det.
