### ISSUE TITLE
Implmenter et system der gør det muligt at lave version specifikke widgets/moduler

### ISSUE THREAD

**Issue by Andi6969** [TFSMads/transporter#15]
Ville være super rart hvis man kunne bruge den nye widget metode i labymod 4 med addonet istedet for at gå ind under gui moduler

**Comment by TFSMads** [comment]
Der er nok ikke noget der kommer til at blive tilføjet da det ville kræve en labymod 4 specifik implementation og Transporter Addon understøtter flere versioner af Minecraft.

**Comment by Andi6969** [comment]
Ka godt se hvad du mener men at some point kommer alle til at upgrade til labymod 4

**Comment by TFSMads** [comment]
Jeg har nu omkodet gui modul/widget systemet så det understøtter version specefikke implementationer. Hvis ikke en understøttet version har et en custom widget implementation vil der blive brugt en standard implmentation der virker med alle versioner.

Jeg har lavet en implementation til labymod 4 der benytter labymod 4 gui widget systemet.
