### ISSUE TITLE
LabyMod-widgets overlapper F3 (kun testet på LabyMod4).

### ISSUE THREAD

**Issue by TheAncientBook** [TFSMads/transporter#17]
![image](https://github.com/TFSMads/transporter/assets/61551799/d8d116de-8bba-4f9b-86ad-eb9f68664289)

**Comment by TFSMads** [comment]
Det er nu fikset i alle versioner af transporter addon. Når debug menuen åbnes bliver alle gui moduler skjult lige som i labymod 4
