### ISSUE TITLE
Deaktivere Autotransporter put ved join af andre servere

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#21]
Det kunne være lækkert at hvis man joiner en server som ikke er en lobby så deaktivere den automatisk autotransporter put, da overraskende mange glemmer at slå det fra når de joiner en server og bare ender med at spamme en masse kommandoer.

**Comment by TFSMads** [comment]
Det er nu tilføjet. Det kommer sammen med næste update.
