### ISSUE TITLE
Bugs i maskinrummet

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#28]
Når man bruger auto get i maskinrummet bliver den ved med at tage ud selvom at ens inventory er fyldt og auto put virker slet ikke, ser ikke ud til at den kan se hvad man har i sin inventory derinde. mistænker at det skyldes at serveren er i nyere version end de andre

**Comment by TFSMads** [comment]
Lav prioritet indtil maskinrummet åbner igen

**Comment by TFSMads** [comment]
wont fix indtil maskinrummet åbner igen
