### ISSUE TITLE
Forslag: En keybind som toggler eller åbner Sign tools menuen

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#30]
Kunne være lækkert med en keybind som toggler om Åben editor er til eller fra 
![image](https://github.com/TFSMads/transporter/assets/85518723/bc408a6d-944c-4b9a-aa3b-4a7ad61a167e)
Kunne også tilføjes som en widget så man ved det inden at man prøver at placere et skilt

**Comment by TFSMads** [comment]
#36 Dette er også tilføjet i denne pull request

**Comment by ChralleDK** [comment]
Den nye keybind indstilling hedder bare dette 
![image](https://github.com/user-attachments/assets/8af48890-35c0-48ca-b6ce-7edb52f7bec2)
