### ISSUE TITLE
Forslag: Set Åben editor i sign tools til ON ved start af spil

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#31]
Oplever tit at når jeg prøver at placere et skilt så er det bare tomt da jeg har glemt at slå Åben editor til ON igen. Kunne være lækkert hvis det gjorde det automatisk ved opstart af spillet

**Comment by TFSMads** [comment]
Jeg kunne eventuelt gøre så den altid åbner editoren hvis man ikke har kopieret noget

**Comment by ChralleDK** [comment]
Ja kunne også være en god ide

**Comment by ChralleDK** [comment]
Åbner fint Sign editor gui ved tomt Signtool copy
