### ISSUE TITLE
Benyt labymod 4 settings system

### ISSUE THREAD

**Issue by TFSMads** [TFSMads/transporter#34]
Skift til at bruge labymod 4 addon settings istedet for at omdirigere til transporter settings menu.

**Comment by ChralleDK** [comment]
Når man henter det så bliver alle widgets sat tilbage til endelse formateringen, selvom at den fx siger Punktum og kræver at man vælger en anden formatering før man kan sælge punktum igen

**Comment by ChralleDK** [comment]
Den gør det ved hver genstart ^^

**Comment by TFSMads** [comment]
Det er fikset nu
