### ISSUE TITLE
Balance widget ser ikke kommatal

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#42]
Hvis man sælger så kan den ikke læse komma tal (punktum grundet engelsk)

Prøvede at sælge for 2.77 Ems men den tog 277 Ems fra shop ejerens balance widget
![image](https://github.com/user-attachments/assets/caae5997-477a-4f9c-b433-465e0e024fc7)

**Comment by ChralleDK** [comment]
Tænker godt du har hørt at /balance ikke virker med at sætte værdien i den nyeste beta
Det jeg har oplevet indtil nu er at den tager . i tusind og bruger som komma til istedet for , som er til sidst

Så Hvis jeg fx har 12.345,67 Ems så siger den bare 12 Ems i widget
Hvis jeg har fx. 1.234.567,89 Så kan den slet ikke sætte værdien til noget da der er 2 .

**Comment by TFSMads** [comment]
Det skyldes jeg har ændret det pga. shop beskeder. Jeg skal have tilføjet endnu en tal format (amountf3)

**Comment by TFSMads** [comment]
@ChralleDK kan du ændre hvilke format de forskellige tal er i https://github.com/TFSMads/transporter/blob/bug/balance/core/src/main/resources/transporter/transporter-balance-messages.csv på branchen https://github.com/TFSMads/transporter/tree/bug/balance

Jeg har lige tilføjet amountf3 men har ikke styr på hvilke format diverse beskeder er.

amountf1 er 2,632.32
amountf2 er 2632.32
amountf3 er 2.632,32

**Comment by Andi6969** [comment]
Balance er fixed!
