### ISSUE TITLE
Transporter put mine på serveren tager ikke alle ting mere

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#43]
I den sidste opdatering fra SA fixede de så /Transporter put Mine, kun tager ting fra minerne som sand, quartz, cobblestone, sprucelogs osv.

Så addonnet skal nok vide at den ikke kan putte alle de andre ting ind med /transporter put mine længere

Der er kommet en ny kommando som hedder /transporter put all, som putter alting ind,

Måske man skulle lave sådan at man kan vælge om det kun skal være ting fra minen som den putter ind eller om den skal bruge transporter put all og putte alting ind

**Comment by TFSMads** [comment]
Fikset i https://github.com/TFSMads/transporter/pull/46
