### ISSUE TITLE
Opdatere beskeden på widgets fra /transporter info til /transporter list

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#45]
Har ikke lige set om du har tilføjet det endnu, tænker det ikke så opretter det lige her for en sikkerhedsskyld

Men når man fx henter addonnet for første gang og værdierne ikke er sat, så skriver den at man skal bruge /transporter info, men kommandoen hedder /transporter list, nu

**Comment by TFSMads** [comment]
Det er ændret samt tilføjet til language filen så det er nemmere at ændre
