### ISSUE TITLE
Auto put kommer stadig i chatten

### ISSUE THREAD

**Issue by ChralleDK** [TFSMads/transporter#56]
Hvis man er vip og miner så ens inventory bliver fyldt så putter serveren selv tingene ind i transporteren og sender en besked 
![image](https://github.com/user-attachments/assets/30f21770-c449-412d-90e4-f6f8f5b9a264)
Det kommer stadig i chatten hvilket er ret træls, går også udfra at den ikke opdatere widgets men har ikke lige set det

Fra logs:
[15:35:21] [Client thread/INFO]: [CHAT] Du har nu puttet følgende i din transporter:
[15:35:21] [Client thread/INFO]: [CHAT]  Spruce Log: 2.176

**Comment by ChralleDK** [comment]
Den putter det også hvis man samler noget op så inventoryet bliver fyldt

**Comment by Andi6969** [comment]
Den opdatere widgets ^^

**Comment by Andi6969** [comment]
Vi skal bare have rettet så den ikke sender beskeden i chatten

**Comment by TFSMads** [comment]
Har ikke vip så det bliver lidt svært at tilføje og teste det

**Comment by Andi6969** [comment]
Jeg skal nok lege med det ^^

**Comment by TFSMads** [comment]
Okay👍

**Comment by Andi6969** [comment]
Jeg har sku ik VIP længere. :(

**Comment by Andi6969** [comment]
Dette burde ikke længere være et problem da der bliver lavet en toggle command

**Comment by TFSMads** [comment]
Så lukker jeg bare dette issue som wontfix
