### ISSUE TITLE
Delay (Ticks) fungerer ikke i LabyMod4

### ISSUE THREAD

**Issue by TheAncientBook** [TFSMads/transporter#9]

**Comment by TheAncientBook** [comment]
Kunne også tænkes at ændres til /transporter put mine igen, fordi den tager alt samtidig nu.

**Comment by TFSMads** [comment]
Det ville dog også kræve at vi skrev /transporter info hver eneste gang /transporter mine er blevet brugt for at vide hvad der nu er i transporteren.

**Comment by TFSMads** [comment]
Har fikset problemet med delay ticks nu. Problemet var at Delay ticks maks kunne ændres til 100 og der er 120 ticks cooldown på commands.
